config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "flights#index"
  resources :flights, only: [:index]

end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
    has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
    belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airports = Airport.all
    @Flight = Flight.all
    
    if request.xhr?
      # Filter flights based on the selected departure airport
      if params[:departure_airport_id].present?
        departure_airport = Airport.find(params[:departure_airport_id])
        @flights = @flights.where(departure_airport: departure_airport)
      end

      # Filter flights based on the selected arrival airport
      if params[:arrival_airport_id].present?
        arrival_airport = Airport.find(params[:arrival_airport_id])
        @flights = @flights.where(arrival_airport: arrival_airport)
      end

      # Filter flights based on the selected flight date
      if params[:flight_date].present?
        selected_date = Date.parse(params[:flight_date])
        @flights = @flights.where(flight_date: selected_date)
      end

      # Filter flights based on the selected number of passengers (1-4)
      if params[:num_passengers].present?
        num_passengers = params[:num_passengers].to_i
        @flights = @flights.where(num_passengers: num_passengers)
      end

      render turbo_stream: turbo_stream.replace("flight-results", partial: "flights/flight_results")
    end

  end

  private

  def search_flights
    if params[:departure_airport_id].present? && params[:arrival_airport_id].present?
      Flight.where(departure_airport_id: params[:departure_airport_id], arrival_airport_id: params[:arrival_airport_id])
      flights_url
    else
      [] # Return an empty array
    end

    query = Flight.all

    if params[:departure_airport_id].present?
      query = query.where(departure_airport_id: params[:departure_airport_id])
    end

    if params[:arrival_airport_id].present?
      query = query.where(arrival_airport_id: params[:arrival_airport_id])
    end

    if params[:num_passengers].present?
      query = query.where(num_passengers: params[:num_passengers])
    end

    if params[:flight_date].present?
      query = query.where(flight_date: params[:flight_date])
    end

    query

  end

  helper_method :date_dropdown_options

  def date_dropdown_options
    Flight.where.not(flight_date: nil).pluck(:flight_date).uniq.map { |date| [date.strftime('%Y-%m-%d'), date] }
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/index.html.erb
<h1>Flight Search</h1>

<!-- Search form with Turbo Streams -->
<%= form_with(url: flights_path, method: :get, data: { turbo: true, action: "submit->handleSearch" }) do |form| %>
  <%= form.label :departure_airport_id, 'Departure Airport:' %>
  <%= form.select :departure_airport_id, options_for_select(@airports.map { |airport| [airport.code, airport.id] }) %>
  <br>
  <%= form.label :arrival_airport_id, 'Arrival Airport:' %>
  <%= form.select :arrival_airport_id, options_for_select(@airports.map { |airport| [airport.code, airport.id] }) %>
  <br>
  <%= form.label :num_passengers, 'Number of Passengers:' %>
  <%= form.select :num_passengers, options_for_select(1..4) %>
  <br>
  <%= form.label :flight_date, 'Flight Date:' %>
  <%= form.select :flight_date, options_for_select(date_dropdown_options) %>
  <br>
  <%= form.submit 'Search Flights' %>
<% end %>

<!-- Display flight results -->
<% if @flights.present? %>
  <h2>Flight Results</h2>
  <ul>
    <% @flights.each do |flight| %>
      <li>
        Flight from <%= flight.departure_airport.code %> to <%= flight.arrival_airport.code %>
        on <%= flight.flight_date.strftime('%Y-%m-%d') %>
        with <%= flight.num_passengers %> passengers.
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No flights found.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>